### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by operationairstrike** [ELginas/discord-image-gallery#1]
![Screenshot_2023-05-13-18-40-30-623_com.termux.jpg](https://github.com/ELginas/discord-image-gallery/assets/127621147/73ec2a16-6ac0-45d7-ab1f-f71b3213e06e)

Idk what happened.

**Comment by ELginas** [comment]
There is no need to use NodeJS to get the website working. You only need to set `DISCORD_TOKEN` in `index.js` and then open `index.html` in your browser (no need to setup a web server).

**Comment by operationairstrike** [comment]
I opened the website in my browser and if I paste the channel link it won't load

**Comment by ELginas** [comment]
You shouldn't paste the channel link, you only need the channel ID. Look over the instructions carefully [here](https://github.com/ELginas/discord-image-gallery#usage).

**Comment by operationairstrike** [comment]
Oh Shit ok
