### ISSUE TITLE
Unknown fetch error.

### ISSUE THREAD

**Issue by dodgynut** [ELginas/discord-image-gallery#2]
Randomly stopped working 
Console
Failed to load resource: the server responded with a status of 400 ()

**Comment by ELginas** [comment]
Can't reproduce.

**Comment by dodgynut** [comment]
![Screenshot 2023-09-17 185549](https://github.com/ELginas/discord-image-gallery/assets/144963742/aadc1416-94dc-4519-b4d1-ee59fe6c3c6b)

![Screenshot 2023-09-17 18572622](https://github.com/ELginas/discord-image-gallery/assets/144963742/a42f8d45-6439-40cc-b3ff-b435081cd49e)

![Screenshot 2023-09-17 185913](https://github.com/ELginas/discord-image-gallery/assets/144963742/8f7ce464-86c0-4ee4-b9a0-7cdb1f9497d9)

I don't know what I am doing wrong then.
Discord token changed after posting screenshots

**Comment by ELginas** [comment]
How does the request look like in Network tab?

**Comment by dodgynut** [comment]
![image](https://github.com/ELginas/discord-image-gallery/assets/144963742/e6bd9ec6-e477-4920-8083-907791f1c38c)
![22222222222222222222](https://github.com/ELginas/discord-image-gallery/assets/144963742/da973ca0-507f-40ef-837e-ace3927efebc)

**Comment by ELginas** [comment]
What about request/response body content?

**Comment by dodgynut** [comment]
Error 400 response tab
![Screensho52323232t 2023-09-18 183003](https://github.com/ELginas/discord-image-gallery/assets/144963742/dcd0db03-3281-4ce0-bb2f-2ed2fbfd27a5)
And the other one

![2222222222Screenshot 2023-09-18 183054](https://github.com/ELginas/discord-image-gallery/assets/144963742/f6d46492-cefc-439b-9ef4-903636b94cb0)
![Screensh555555555555ot 2023-09-18 183130](https://github.com/ELginas/discord-image-gallery/assets/144963742/544d04e8-8bcf-45e8-afad-71b04aef4ca0)

**Comment by ELginas** [comment]
Well it looks like it complains about channel type. I have only tested basic text channels, DMs and group chats. I don't know what channel type it is but I have not tested how VC text chats or forums behave.

**Comment by dodgynut** [comment]
This is a normal general chat. I have used it before and it worked fine now a couple of months later it started giving an unknown fetch error

**Comment by ELginas** [comment]
Does it work for other channels on the same server and what about other servers?

**Comment by dodgynut** [comment]
It works for DMs and group chats. other text  channels do not work the same on different servers

**Comment by ELginas** [comment]
Apparently Discord updated and now channel search for guilds are replaced with guild-wide search. Updated code accordingly. If the issue is solved, let me know.

**Comment by dodgynut** [comment]
Everything is working fine now
